site_name: nunu-Wiki
site_url: http://yangxu286.github.io/nunu-Wiki
site_author: yangxu286
theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - attr_list

plugins:
  - search